services:
  okane_finance_backend:
    build:
      context: ../
      dockerfile: ./docker/backend/Dockerfile
      args:
        APP_VERSION: "0.0.1-SNAPSHOT"
    container_name: okane_finance_backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://okane_finance_db:5432/okane_finance
      - SPRING_DATASOURCE_USERNAME=okane
      - SPRING_DATASOURCE_PASSWORD=okane
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    networks:
      - okane_network
    ports:
      - "8080:8080"
#    entrypoint: /bin/sh
#    tty: true
#    stdin_open: true
  db:
    image: postgres
    container_name: okane_finance_db
    environment:
      - POSTGRES_USER=okane
      - POSTGRES_PASSWORD=okane
      - POSTGRES_DB=okane_finance
    networks:
      - okane_network
    ports:
      - "5432:5432"

networks:
  okane_network:
    driver: bridge
